### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mflynn-lanl** [saketkc/pysradb#71] opened 2020-10-01 17:24 UTC
**Describe the bug**
ModuleNotFoundError when importing SRAweb

**To Reproduce**
`conda create -c bioconda -n pysradb PYTHON=3 pysradb`
`conda activate pysradb`
`python`
>>> from pysradb import SRAweb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysradb.sraweb'

**Desktop (please complete the following information):**
 - OS: macOS Mojave version 10.14.6
 - Python version 3.7.9
 - pysradb 0.9.0

**Comment by saketkc** [comment] 2020-10-01 17:34
Thanks for the bug report @mflynn-lanl! I suspect this is coming from a pip+conda mixup.
Note that the latest stable version of pysradb is `0.11.1`. I think you have `0.9.0` installed through pip? bioconda also has the latest pysradb.

 Here's a Google colab notebook for demonstration: https://colab.research.google.com/drive/15DIzoN04KeQosXSe1JRlDyKqIoKb9V-o?usp=sharing

I would suggest deleting the `pysradb` environment and redoing the steps:
```
conda env remove -n pysradb
conda create -c bioconda -n pysradb PYTHON=3 pysradb
conda activate pysradb
```
Newer versions of conda also support deleting automatically if you create an environment with a name that already exists.
Please feel free to reopen if you are still facing issues.

**Comment by mflynn-lanl** [comment] 2020-10-01 17:41
I used the exact steps you suggested

**Comment by mflynn-lanl** [comment] 2020-10-01 17:46
I was able to install the latest version using pip

**Comment by saketkc** [comment] 2020-10-01 17:47
Thanks for the update @mflynn-lanl! I am unable to reproduce this either using pip or conda, so I will go ahead and (re)close this.

**Closed by saketkc** 2020-10-01 17:47 UTC
Labels: bug
